# Generated by Django 3.2.3 on 2022-05-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiek', models.IntegerField()),
                ('plec', models.CharField(choices=[('k', 'Kobieta'), ('m', 'Mężczyzna'), ('i', 'Inne')], max_length=1)),
                ('wyksztalcenie', models.IntegerField(choices=[(1, 'Podstawowe'), (2, 'Średnie'), (3, 'Wyższe')])),
                ('Czy_lubisz_szczepienia', models.IntegerField(choices=[(1, 'Lubię'), (2, 'Średnio'), (3, 'Nie ufam')])),
            ],
        ),
    ]
