# Generated by Django 4.0.3 on 2022-03-17 19:16

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiek', models.IntegerField()),
                ('plec', models.CharField(choices=[('k', 'Kobieta'), ('m', 'Mężczyzna'), ('i', 'Inne')], max_length=1)),
                ('wyksztalcenie', models.IntegerField(choices=[(1, 'Podstawowe'), (2, 'Średnie'), (3, 'Wyższe')])),
            ],
        ),
    ]
