# Generated by Django 3.2.3 on 2022-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odpowiedz2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyksztalcenie', models.IntegerField(choices=[(1, 'Podstawowe'), (2, 'Średnie'), (3, 'Wyższe')])),
                ('geeks_field', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='odpowiedz',
            name='Czy_lubisz_szczepienia',
        ),
        migrations.RemoveField(
            model_name='odpowiedz',
            name='geeks_field',
        ),
        migrations.RemoveField(
            model_name='odpowiedz',
            name='wyksztalcenie',
        ),
    ]
