# Generated by Django 3.2.3 on 2022-05-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0002_auto_20220505_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Odpowiedz2',
        ),
        migrations.RemoveField(
            model_name='odpowiedz',
            name='plec',
        ),
    ]
